services:
  - type: web
    name: apex-cdn-simulator
    env: go
    buildCommand: go build -o app_server cmd/app/main.go && go build -o router_server cmd/router/main.go && go build -o simulator main.go
    startCommand: ./simulator
    envVars:
      - key: PORT
        value: 8080
      - key: WEB_DIR
        value: ./web
      - key: MOCK_MODE
        value: "true"
